In [9]:
def get_line(x1, y1, x2, y2):
    points = []
    issteep = abs(y2-y1) > abs(x2-x1)
    if issteep:
        x1, y1 = y1, x1
        x2, y2 = y2, x2
    rev = False
    if x1 > x2:
        x1, x2 = x2, x1
        y1, y2 = y2, y1
        rev = True
    deltax = x2 - x1
    deltay = abs(y2-y1)
    error = int(deltax / 2)
    y = y1
    ystep = None
    if y1 < y2:
        ystep = 1
    else:
        ystep = -1
    for x in range(x1, x2 + 1):
        if issteep:
            points.append((y, x))
        else:
            points.append((x, y))
        error -= deltay
        if error < 0:
            y += ystep
            error += deltax
    # Reverse the list if the coordinates were reversed
    if rev:
        points.reverse()
    return points

In [10]:
get_line(100,100,0,0)

[(100, 100),
 (99, 99),
 (98, 98),
 (97, 97),
 (96, 96),
 (95, 95),
 (94, 94),
 (93, 93),
 (92, 92),
 (91, 91),
 (90, 90),
 (89, 89),
 (88, 88),
 (87, 87),
 (86, 86),
 (85, 85),
 (84, 84),
 (83, 83),
 (82, 82),
 (81, 81),
 (80, 80),
 (79, 79),
 (78, 78),
 (77, 77),
 (76, 76),
 (75, 75),
 (74, 74),
 (73, 73),
 (72, 72),
 (71, 71),
 (70, 70),
 (69, 69),
 (68, 68),
 (67, 67),
 (66, 66),
 (65, 65),
 (64, 64),
 (63, 63),
 (62, 62),
 (61, 61),
 (60, 60),
 (59, 59),
 (58, 58),
 (57, 57),
 (56, 56),
 (55, 55),
 (54, 54),
 (53, 53),
 (52, 52),
 (51, 51),
 (50, 50),
 (49, 49),
 (48, 48),
 (47, 47),
 (46, 46),
 (45, 45),
 (44, 44),
 (43, 43),
 (42, 42),
 (41, 41),
 (40, 40),
 (39, 39),
 (38, 38),
 (37, 37),
 (36, 36),
 (35, 35),
 (34, 34),
 (33, 33),
 (32, 32),
 (31, 31),
 (30, 30),
 (29, 29),
 (28, 28),
 (27, 27),
 (26, 26),
 (25, 25),
 (24, 24),
 (23, 23),
 (22, 22),
 (21, 21),
 (20, 20),
 (19, 19),
 (18, 18),
 (17, 17),
 (16, 16),
 (15, 15),
 (14, 14),
 (13, 13),
 (12, 12),
 (11, 11),
 (10, 10

In [11]:
def getLine(x1,y1,x2,y2,res):
    rev = False
    if x1==x2: ## Perfectly horizontal line, can be solved easily
        return [(x1,i) for i in range(y1,y2,int(abs(y2-y1)/(y2-y1)))]
    else: ## More of a problem, ratios can be used instead
        if x1>x2: ## If the line goes "backwards", flip the positions, to go "forwards" down it.
            rev = True
            x=x1
            x1=x2
            x2=x
            y=y1
            y1=y2
            y2=y
        slope=(y2-y1)/(x2-x1) ## Calculate the slope of the line
        line=[]
        i=0
        while x1+i < x2: ## Keep iterating until the end of the line is reached
            i+=res
            line.append((x1+i,y1+slope*i)) ## Add the next point on the line
        if rev:
            line.reverse()

        return line ## Finally, return the line!



In [15]:
getLine(0,0,100,100, 0.1)

[(0.1, 0.1),
 (0.2, 0.2),
 (0.30000000000000004, 0.30000000000000004),
 (0.4, 0.4),
 (0.5, 0.5),
 (0.6, 0.6),
 (0.7, 0.7),
 (0.7999999999999999, 0.7999999999999999),
 (0.8999999999999999, 0.8999999999999999),
 (0.9999999999999999, 0.9999999999999999),
 (1.0999999999999999, 1.0999999999999999),
 (1.2, 1.2),
 (1.3, 1.3),
 (1.4000000000000001, 1.4000000000000001),
 (1.5000000000000002, 1.5000000000000002),
 (1.6000000000000003, 1.6000000000000003),
 (1.7000000000000004, 1.7000000000000004),
 (1.8000000000000005, 1.8000000000000005),
 (1.9000000000000006, 1.9000000000000006),
 (2.0000000000000004, 2.0000000000000004),
 (2.1000000000000005, 2.1000000000000005),
 (2.2000000000000006, 2.2000000000000006),
 (2.3000000000000007, 2.3000000000000007),
 (2.400000000000001, 2.400000000000001),
 (2.500000000000001, 2.500000000000001),
 (2.600000000000001, 2.600000000000001),
 (2.700000000000001, 2.700000000000001),
 (2.800000000000001, 2.800000000000001),
 (2.9000000000000012, 2.9000000000000012),
 

In [16]:
import numpy as np

In [30]:
n = 723
m= 362

In [33]:
a = np.arange(n//2)
a

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
       117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129,
       130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142,
       143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155,
       156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168,
       169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 18

In [34]:
b = np.arange(m/2)
b

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
       117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129,
       130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142,
       143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155,
       156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168,
       169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 18

In [29]:
b = np.arange(n//2+1,n)
b

array([362, 363, 364, 365, 366, 367, 368, 369, 370, 371, 372, 373, 374,
       375, 376, 377, 378, 379, 380, 381, 382, 383, 384, 385, 386, 387,
       388, 389, 390, 391, 392, 393, 394, 395, 396, 397, 398, 399, 400,
       401, 402, 403, 404, 405, 406, 407, 408, 409, 410, 411, 412, 413,
       414, 415, 416, 417, 418, 419, 420, 421, 422, 423, 424, 425, 426,
       427, 428, 429, 430, 431, 432, 433, 434, 435, 436, 437, 438, 439,
       440, 441, 442, 443, 444, 445, 446, 447, 448, 449, 450, 451, 452,
       453, 454, 455, 456, 457, 458, 459, 460, 461, 462, 463, 464, 465,
       466, 467, 468, 469, 470, 471, 472, 473, 474, 475, 476, 477, 478,
       479, 480, 481, 482, 483, 484, 485, 486, 487, 488, 489, 490, 491,
       492, 493, 494, 495, 496, 497, 498, 499, 500, 501, 502, 503, 504,
       505, 506, 507, 508, 509, 510, 511, 512, 513, 514, 515, 516, 517,
       518, 519, 520, 521, 522, 523, 524, 525, 526, 527, 528, 529, 530,
       531, 532, 533, 534, 535, 536, 537, 538, 539, 540, 541, 54

In [40]:
b[n/4:]

array([180])

In [50]:
b[-90:]

array([ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
       117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129,
       130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142,
       143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155,
       156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168,
       169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180])

In [51]:
a = [1,3,4,4]


In [55]:
path = [
    [0,0],
    [0,1],
    [0,2],
    [1,2],
    [2,2],
    [3,2],
    [4,2],
    [4,3],
    [4,4]
]

In [56]:
path

[[0, 0], [0, 1], [0, 2], [1, 2], [2, 2], [3, 2], [4, 2], [4, 3], [4, 4]]

In [ ]:
def smooth(path, weight_data = 0.5, weight_smooth = 0.1, tolerance= 0.001):
    newpath = [[0 for row in range(path[0])] for col in range(len(path))]
    for i in range(len(path)):
        for j in range(len(path[0])):
            new_path[i][j] = path[i][j]
    change = tolerance
    while change >= tolerance:
        for i in range(1, len(path)-1):
        

In [63]:
newpath = [[0 for row in range(len(path[0]))] for col in range(len(path))]

In [64]:
newpath

[[0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0]]

In [69]:


# -----------
# User Instructions
#
# Define a function smooth that takes a path as its input
# (with optional parameters for weight_data, weight_smooth,
# and tolerance) and returns a smooth path. The first and 
# last points should remain unchanged.
#
# Smoothing should be implemented by iteratively updating
# each entry in newpath until some desired level of accuracy
# is reached. The update should be done according to the
# gradient descent equations given in the instructor's note
# below (the equations given in the video are not quite 
# correct).
# -----------

from copy import deepcopy

# thank you to EnTerr for posting this on our discussion forum
def printpaths(path,newpath):
    for old,new in zip(path,newpath):
        print '['+ ', '.join('%.3f'%x for x in old) + \
               '] -> ['+ ', '.join('%.3f'%x for x in new) +']'

# Don't modify path inside your function.
path = [[0, 0],
        [0, 1],
        [0, 2],
        [1, 2],
        [2, 2],
        [3, 2],
        [4, 2],
        [4, 3],
        [4, 4]]

def smooth(path, weight_data = 0.5, weight_smooth = 0.1, tolerance = 0.000001):

    # Make a deep copy of path into newpath
    newpath = deepcopy(path)

    #######################
    ### ENTER CODE HERE ###
    #######################
    while True:
        totalChange = 0.
        for i in range(len(path)):
            if i != 0 and i != (len(path) - 1):
                for dim in range(len(path[i])):
                    oldVal = newpath[i][dim]
                    newpath[i][dim] = newpath[i][dim] + \
                        weight_data * (path[i][dim] - newpath[i][dim]) + \
                        weight_smooth * (newpath[i+1][dim] + newpath[i-1][dim] - 2 * newpath[i][dim])
                    totalChange += abs(oldVal - newpath[i][dim])
        if totalChange < tolerance:
            break
    return newpath # Leave this line for the grader!

printpaths(path,smooth(path))

[0.000, 0.000] -> [0.000, 0.000]
[0.000, 1.000] -> [0.021, 0.979]
[0.000, 2.000] -> [0.149, 1.851]
[1.000, 2.000] -> [1.021, 1.979]
[2.000, 2.000] -> [2.000, 2.000]
[3.000, 2.000] -> [2.979, 2.021]
[4.000, 2.000] -> [3.851, 2.149]
[4.000, 3.000] -> [3.979, 3.021]
[4.000, 4.000] -> [4.000, 4.000]


In [83]:
a = [1,2,3]

In [94]:
path = np.array([[0, 0],
        [0, 1],
        [0, 2],
        [1, 2],
        [2, 2],
        [3, 2],
        [4, 2],
        [4, 3],
        [4, 4]]).T


In [95]:
path

array([[0, 0, 0, 1, 2, 3, 4, 4, 4],
       [0, 1, 2, 2, 2, 2, 2, 3, 4]])

In [96]:
path[0].sum()

18

In [106]:
path[0].sum()/path[0].shape

array([2])

In [105]:
path.shape

(2, 9)